import type { ThemeSpec } from './types';

/**
 * The registry's data: eleven themes, and only the colours a designer chose.
 *
 * Eleven, not ten: the ten the brief names, plus `kondukt` — the warm M3 theme
 * this app has always shipped, carried forward as the default so an install
 * that never opens the Themes section renders exactly what it renders today.
 * Everything below `surface`/`text` that the app needs is derived from these
 * values by `derive.ts`.
 *
 * READ THE DIALECT COLUMN. Three themes are dark by design. The dialect is the
 * mode a theme belongs to — its native skin — and the Light/Dark control can
 * still render any theme in either mode; what the dialect decides is which
 * neutral family the theme's accent and gradient are read against.
 */
export const THEME_SPECS: readonly ThemeSpec[] = [
  {
    id: 'kondukt',
    name: 'Kondukt Warm',
    note: 'The app’s own warm palette, unchanged.',
    dialect: 'light',
    surface: '#FDF7F3',
    text: '#221A15',
    primary: '#E65100',
    secondary: '#FFB300',
    // The app has no separate accent hue: its accent IS its primary, which is
    // why `tintedGlass.accent` and `palette.primarySolid` are the same colour
    // in the bundle as shipped.
    accent: '#E65100',
    gradient: ['#FBC9A8', '#F4F7FB', '#C6D9E8'],
    // The AUTHORED palette, and the only theme in the registry that carries
    // one. These are the 106 values the app has always rendered, kept as data
    // rather than as an accident of a formula: each one is a decision about how
    // this app looks, and a six-colour seed cannot recover them. They apply at
    // the default appearance only, so `contrast: 'high'` and Dynamic Accent
    // still re-step this theme rather than being pinned by them. Every other
    // theme below is derived from its six colours and needs no overrides at
    // all.
  overrides: {
    light: {
      palette: {
        primary: '#E65100',
        onPrimary: '#FFFFFF',
        primaryContainer: '#FFE6D2',
        onPrimaryContainer: '#4E2200',
        primarySolid: '#C2410C',
        secondary: '#FFB300',
        onSecondary: '#3D2E00',
        secondaryContainer: '#FFEFC7',
        onSecondaryContainer: '#4A3600',
        tertiary: '#546E7A',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#DDE6EA',
        onTertiaryContainer: '#162B33',
        error: '#BA1A1A',
        onError: '#FFFFFF',
        errorContainer: '#FFDAD6',
        onErrorContainer: '#410002',
        success: '#3E7D44',
        onSuccess: '#FFFFFF',
        successContainer: '#D9EFDB',
        onSuccessContainer: '#123A18',
        warning: '#8A6100',
        onWarning: '#FFFFFF',
        warningContainer: '#FFEFC7',
        onWarningContainer: '#4A3600',
        background: '#FDF7F3',
        surface: '#FDF7F3',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#F7EFE9',
        surfaceContainer: '#F2E9E2',
        surfaceContainerHigh: '#ECE3DC',
        onSurface: '#221A15',
        onSurfaceVariant: '#53433B',
        outline: '#85736B',
        outlineVariant: '#D7C2B7',
        scrim: 'rgba(34, 26, 21, 0.32)',
      },
      glass: {
        backdrop: '#F4F7FB',
        fieldTopLeft: ['#FBC9A8', '#F6E3D4', '#F4F7FB'],
        fieldBottomRight: ['#C6D9E8', '#E4E9F2', '#F4F7FB'],
        tint: 'rgba(255, 255, 255, 0.58)',
        tintStrong: 'rgba(255, 255, 255, 0.72)',
        rim: 'rgba(255, 255, 255, 0.85)',
        rimFaint: 'rgba(255, 255, 255, 0.34)',
        shadow: 'rgba(90, 106, 130, 0.16)',
        grain: 'rgba(120, 130, 150, 0.5)',
        onGlass: '#1A2029',
        onGlassVariant: '#4A5568',
        accentPrimary: '#8F3A00',
        accentSecondary: '#6B4B00',
        accentTertiary: '#334A56',
        blur: 18,
      },
      accent: {
        primary: { fg: '#E65100', container: '#FFE6D2', onContainer: '#4E2200' },
        secondary: { fg: '#8A6100', container: '#FFEFC7', onContainer: '#4A3600' },
        tertiary: { fg: '#546E7A', container: '#DDE6EA', onContainer: '#162B33' },
      },
      onSecondaryRamp: { primary: '#3D2E00', detail: '#4A3820', muted: '#57431C', faint: '#604B10' },
      amberSurface: { rule: '#E0C489', border: '#E8C97A' },
      tintedGlass: { accent: 'rgb(194, 65, 12)', error: 'rgb(186, 26, 26)' },
      onPrimarySolid: '#FFFFFF',
    },
    dark: {
      palette: {
        primary: '#FFB68B',
        onPrimary: '#4E2200',
        primaryContainer: '#6E3400',
        onPrimaryContainer: '#FFDCC4',
        primarySolid: '#C2410C',
        secondary: '#FFD066',
        onSecondary: '#3D2E00',
        secondaryContainer: '#5C4300',
        onSecondaryContainer: '#FFEFC7',
        tertiary: '#A9C7D4',
        onTertiary: '#162B33',
        tertiaryContainer: '#334A56',
        onTertiaryContainer: '#DDE6EA',
        error: '#FFB4AB',
        onError: '#410002',
        errorContainer: '#93000A',
        onErrorContainer: '#FFDAD6',
        success: '#8FD79B',
        onSuccess: '#123A18',
        successContainer: '#1F4526',
        onSuccessContainer: '#C3EDC9',
        warning: '#FFD066',
        onWarning: '#3D2E00',
        warningContainer: '#5C4300',
        onWarningContainer: '#FFEFC7',
        background: '#17120E',
        surface: '#17120E',
        surfaceContainerLowest: '#0F0B09',
        surfaceContainerLow: '#221B16',
        surfaceContainer: '#2A221C',
        surfaceContainerHigh: '#352B24',
        onSurface: '#F3EAE2',
        onSurfaceVariant: '#D7C2B7',
        outline: '#A08D84',
        outlineVariant: '#53433B',
        scrim: 'rgba(0, 0, 0, 0.55)',
      },
      glass: {
        backdrop: '#12161C',
        fieldTopLeft: ['#4A2C18', '#2A2118', '#12161C'],
        fieldBottomRight: ['#16283A', '#1B2330', '#12161C'],
        tint: 'rgba(255, 255, 255, 0.1)',
        tintStrong: 'rgba(255, 255, 255, 0.18)',
        rim: 'rgba(255, 255, 255, 0.28)',
        rimFaint: 'rgba(255, 255, 255, 0.14)',
        shadow: 'rgba(0, 0, 0, 0.5)',
        grain: 'rgba(255, 255, 255, 0.4)',
        onGlass: '#ECE7E1',
        onGlassVariant: '#B9AFA6',
        accentPrimary: '#FFB68B',
        accentSecondary: '#FFD066',
        accentTertiary: '#A9C7D4',
        blur: 18,
      },
      accent: {
        primary: { fg: '#FFB68B', container: '#6E3400', onContainer: '#FFDCC4' },
        secondary: { fg: '#FFD066', container: '#5C4300', onContainer: '#FFEFC7' },
        tertiary: { fg: '#A9C7D4', container: '#334A56', onContainer: '#DDE6EA' },
      },
      onSecondaryRamp: { primary: '#3D2E00', detail: '#4A3820', muted: '#57431C', faint: '#604B10' },
      amberSurface: { rule: '#E0C489', border: '#E8C97A' },
      tintedGlass: { accent: 'rgb(194, 65, 12)', error: 'rgb(186, 26, 26)' },
      onPrimarySolid: '#FFFFFF',
    },
  },
  },
  {
    id: 'sunset-transit',
    name: 'Sunset Transit',
    note: 'Orange light with a cool morning edge.',
    dialect: 'light',
    surface: '#FFFFFF',
    text: '#242424',
    primary: '#FF6B00',
    secondary: '#FFB000',
    accent: '#FF3D00',
    gradient: ['#FFF1E6', '#FFE0C2', '#DCEEFF'],
  },
  {
    id: 'orange-sky',
    name: 'Orange Sky',
    note: 'Warm sky over a bright, open surface.',
    dialect: 'light',
    surface: '#FFFFFF',
    text: '#202124',
    primary: '#FF6D00',
    secondary: '#FFB300',
    accent: '#FF4D00',
    gradient: ['#FFE0CC', '#F5E8DF', '#D9ECFF'],
  },
  {
    id: 'golden-route',
    name: 'Golden Route',
    note: 'A golden body on a warm paper surface.',
    dialect: 'light',
    surface: '#FFFCF5',
    text: '#292929',
    primary: '#F57C00',
    secondary: '#FFC107',
    accent: '#E65100',
    gradient: ['#FFF3D6', '#FFE8B6', '#FFF9ED'],
  },
  {
    id: 'coral-cream',
    name: 'Coral Cream',
    note: 'Coral with a cream wash behind it.',
    dialect: 'light',
    surface: '#FFFFFF',
    text: '#252525',
    primary: '#F4511E',
    secondary: '#FF9800',
    accent: '#E53935',
    gradient: ['#FFE3D8', '#FFF0E3', '#FFF3D9'],
  },
  {
    id: 'orange-mint',
    name: 'Orange Mint',
    note: 'Warm orange with a mint counterweight.',
    dialect: 'light',
    surface: '#FFFFFF',
    text: '#202124',
    primary: '#F4511E',
    secondary: '#FFB300',
    accent: '#00897B',
    gradient: ['#FFF0E6', '#E9F5EF', '#DDF5EA'],
  },
  {
    id: 'orange-lavender',
    name: 'Orange Lavender',
    note: 'A violet accent that still reads as this app.',
    dialect: 'light',
    surface: '#FFFFFF',
    text: '#252525',
    primary: '#F4511E',
    secondary: '#FF9800',
    accent: '#6C63FF',
    gradient: ['#FFE5D8', '#F4EDFF', '#E9E3FF'],
  },
  {
    id: 'cyber-summer',
    name: 'Cyber Summer',
    note: 'Coral into mint, with a teal accent.',
    dialect: 'light',
    surface: '#FFFFFF',
    text: '#17202A',
    primary: '#FF5C35',
    secondary: '#FFD166',
    accent: '#00C2A8',
    gradient: ['#FFF0D5', '#FFE1EC', '#D9F8F1'],
  },
  {
    id: 'cyber',
    name: 'Cyber',
    note: 'Cyan on ink, violet second, magenta edge.',
    dialect: 'dark',
    surface: '#121C2E',
    text: '#F5F7FF',
    primary: '#00E5FF',
    secondary: '#7C4DFF',
    accent: '#FF2BD6',
    gradient: ['#08111F', '#101A33', '#1A0F2E'],
  },
  {
    id: 'cyber-orange',
    name: 'Cyber Orange',
    note: 'The warm brand, lit for a night cabin.',
    dialect: 'dark',
    surface: '#1B1714',
    text: '#FFF7EF',
    primary: '#FF6D00',
    secondary: '#FFB300',
    accent: '#00E5FF',
    gradient: ['#160B05', '#21130A', '#07151B'],
  },
  {
    id: 'cyber-summer-night',
    name: 'Cyber Summer Night',
    note: 'The summer theme after sunset.',
    dialect: 'dark',
    surface: '#172334',
    text: '#F7FAFF',
    primary: '#FF7A59',
    secondary: '#FFD166',
    accent: '#00D9FF',
    gradient: ['#101827', '#18283A', '#182034'],
  },
] as const;

/**
 * The theme an install opens on.
 *
 * `kondukt` is the answer and has to stay it: this id is what
 * `getTheme()` returns when nothing has been persisted, and every one of the
 * forty-odd components reads through it.
 */
export const DEFAULT_THEME_ID = 'kondukt';